scanner:
    diff_only: True
    linter: flake8

flake8:
    max-line-length: 120  # Default is 79 in PEP 8
    ignore:  # Errors and warnings to ignore
        - F401
        - F403
        - F405
        - W503
