from typing import Dict

from box.box import Box as Box

class SBox(Box):
    @property
    def dict(self) -> Dict: ...
    @property
    def json(self) -> str: ...
    @property
    def yaml(self) -> str: ...
    @property
    def toml(self) -> str: ...
    def copy(self) -> "SBox": ...
    def __copy__(self) -> "SBox": ...

class DDBox(Box): ...
