package:
  name: python-box
  version: 3.1.1

source:
  path: ../../

requirements:
  build:
    - PyYAML
    - pytest-runner

  run:
    - PyYAML

test:
  imports:
    - box

about:
  home: https://github.com/cdgriffith/Box
  license: MIT
  summary: "Python dictionaries with advanced dot notation access."
