package:
  name: python-box
  version: 3.1.1

source:
  path: ../../

requirements:
  build:
    - pytest
    - coverage >=3.6
    - tox
    - pytest-cov
    - PyYAML
    - addict
    - dotmap
    - reusables
    - memory_profiler

  run:
    - PyYAML

test:
  imports:
    - box

about:
  home: https://github.com/cdgriffith/Box
  license: MIT
  summary: "Python dictionaries with advanced dot notation access."
